os: linux

language: generic

python: 3.7.1

dist: xenial

services:
  - docker
stages:
  - name: docker-build-master
    if: branch = master
  - name: docker-build-develop
    if: branch = develop
  - name: test

addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
      - liblzo2-dev
      - python3-dev
    update: true

jobs:
  include:
    - stage: docker-build-master
      script:
        - >
          if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
            docker build -t quay.io/ucsc_cgl/cat:latest .
            docker login --username $QUAY_USERNAME --password $QUAY_PASSWORD quay.io
            docker push quay.io/ucsc_cgl/cat:latest
          fi
    - stage: docker-build-develop
      script:
        - >
          if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
            docker build -t quay.io/ucsc_cgl/cat:develop .
            docker login --username $QUAY_USERNAME --password $QUAY_PASSWORD quay.io
            docker push quay.io/ucsc_cgl/cat:develop
          fi
    - stage: test
      script:
        - set -ex
        - pyenv shell 3.7.1
        - pip install --upgrade pip
        - pip install cython wheel setuptools pycparser
        - pip install .
        # Have to screw with toil's settings to get the jobs to
        # actually run properly on such a small VM.
        - sed -i "s/maxDisk = self.physicalDisk/pass/g" /opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/toil/batchSystems/singleMachine.py
        - sed -i "s/maxCores = self.numCores/maxCores = 8/g" /opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/toil/batchSystems/singleMachine.py
        - sed -i "s/maxMemory = self.physicalMemory/pass/g" /opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/toil/batchSystems/singleMachine.py
        - >
          luigi --module cat RunCat --hal=test_data/vertebrates.hal --target-genomes='("hg38", "galGal4")' --ref-genome=mm10
          --workers=2 --config=test_data/test.config --work-dir test_install --out-dir test_install --local-scheduler
          --augustus --augustus-cgp --augustus-pb --assembly-hub --log-level DEBUG
